<div id="text">
    <div class="sidebar">Andrew Valko has made himself the laureate of disconnected encounter: the <strong>master of incomplete ceremony</strong>. Almost without exception, his paintings and drawings are episodes in an ongoing fragmentary narrative in which we are obliged, as viewers, to fill in the details of a story that he only hints at. Valko knows that viewer and voyeur are close in meaning. These radiant paintings glow with <strong>a sense of golden unhappiness</strong>. On the basis of this new work, Andrew Valko legitimately anoints himself the master of the ambiguous gaze. <span class="author">Robert Enright</span><br />

        Andrew Valko's world is bathed in a <strong>dim half-light of a flickering cathode ray tube</strong> illuminating the anonymous rooms and barren hearts of their occupants. His intense style elevates sterile spaces beyond the predictable and achieves an astonishing verisimilitude with a quality of languid disengagement. Looking at his paintings is like running your fingers along the blade of a Henckels knife <strong>thinking it to be the crease in your pants</strong>. <span class="author">Tom Smart</span>

        <p class="credits">Robert Enright has shared his great enthusiasm for the contemporary arts for over two decades. Known for his thoughtful, incisive and authoritative writing, Robert Enright is the founding editor, and currently senior contributing editor, of the highly praised magazine Border Crossings. Unfailing in his support of emerging artists and of the Manitoba arts scene, he has also served as a cultural affairs reporter for CBC Radio, as a contributor to the Globe and Mail and as a research professor in art criticism at the University of Guelph.</p>

        <p class="credits">Tom Smart is the executive director and CEO of the McMichael Canadian Art Collection in Kleinburg, Ontario; and author of <em>Miller Brittain: When the Stars Threw Down Their Spears</em> (with Allen Bentley), <em>Alex Colville: Return</em>, <em>The Art of Mary Pratt: The Substance of Light</em>, <em>The Art of Fred Ross: A Timeless Humanism</em>, and <em>The World of John Hooper</em>. Smart has served in key curatorial positions for numerous art galleries in museums in Canada and the United States.</p></div>
    <div class="maincol">
        Born 1957 in Prague, Czechoslovakia. Came to Canada in 1968. Received his Diploma in Graphic Design and Applied Arts from the Red River Community College in Winnipeg, Manitoba. Also had the opportunity to study printmaking with Toshi Yoshida at Yoshida Hanga Academy in Tokyo, Japan.

        The artist�s exhibition credits include numerous solo exhibitions in the following galleries: Galerie Franklin Silverstone, Montreal, Quebec; Nancy Poole�s Studio, Toronto, Ontario; Cardigan-Milne Gallery and Thomas Gallery, Winnipeg, Manitoba; Assiniboia Gallery and Susan Whitney Gallery, Regina, Saskatchewan; Newzones Gallery, Calgary, Alberta; Monte Clark Gallery, Vancouver, British Columbia; Douglas Udell Gallery, Edmonton, Alberta; Gallery 1C03, University of Winnipeg, Winnipeg, Manitoba; Rosemont Art Gallery, Neil Balkwill Civic Arts Centre, Regina, Saskatchewan; The Art Gallery of Southwestern Manitoba, Brandon, Manitoba; Douglas Udell Gallery, Vancouver, British Columbia and Mayberry Fine Art, Toronto, Ontario. He has also participated in many group shows, both nationally and internationally. His work has been shown at: University of Manitoba, Memorial University of Newfoundland Art Gallery; University of New Brunswick;Acadian University, Wolfville, Nova Scotia; University if Minnesota; Winnipeg Art Gallery; University of Lethbridge,Lethbridge,Alberta; Simon Fraser University, Vancouver, BC; Mayberry Fine Art in Winnipeg, Manitoba and Toronto,Ontario; Norman MacKenzie Art Gallery, Regina, Saskatchewan; Pendulum Gallery, Vancouver, British Columbia; Art Gallery of Greater Victoria; The Frederic Horsman Varley Art Gallery, Ontario; The Grand Theater, Kingston, Ontario; Waddington's Auction House, Toronto, Ontario; Art Court Building, Ottawa, Ontario; Muttart Public Gallery, Calgary, Alberta; The Nickle Art Museum, The University of Calgary; The Art Gallery of Calgary, Calgary, Alberta; Thunder Bay Art Center; Deluth Art Center, Deluth, Minnesota; Plug In Institute of Contemporary Art, Winnipeg, Manitoba;National Art Center, Ottawa, Ontario; Clorendon Lanes Court, Ottawa, Ontario; Duxbury Art Complex Museum, Boston, Massachusetts; Danforth Museum of Art, Massachusetts; Kolding Hal, Frechen, Germany; Taipei Fine Arts Museum, Taipan, Taiwan; R.V.S. Gallery, South Hampton, New York; Kabatoja Gallery in Tokyo; la Maison Rouge, Paris, France; and Le Musee de Arts Modestes, Sete, France. In addition, the artist has been represented at numerous <strong>international Art Fairs</strong> in: Miami, Florida; Boston, Massachusetts; Seattle Washington; San Francisco, California; New York; Chicago, illinois and Toronto, Canana.

        Andrew Valko�s work has been published and reviewed in publications such as Border Crossings, A Magazine of the Arts, The New Yorker Magazine, Elm Street Magazine, Going Places Magazine, Asian Art News, Canadian Art, Style Manitoba, Western Living Magazine, Des Vie Arts, Galleries West Magazine, The Winnipeg Free Press, The Globe and Mail, Uptown Magazine, Regina Leader Post, The Calgary Straight, Calgary Sun, FFWD Calgary, The Georgia Straight, The Edmonton Journal, Toronto Star, The Kingston Whig- Standard, and The Vancouver Sun. He has been the subject of a CBC arts program (ZigZag). In 2001 Postcard Fictions, a book featuring 67 images from the motel and drive-in series of paintings and drawings by Andrew Valko, accompanied by a short story by Toronto writer, Michelle Berry, with foreword by Robert Enright was published by Key Porter Books, Toronto, Canada. Andrew is a recipient of numerous <strong>awards and commissions</strong>. These include being elected to The Royal Canadian Academy of The Arts, receiving Manitoba Arts Council grants, the commission from Canada Post Corporation to illustrate four Pan American Games stamps and the 125th Anniversary of the RCMP commemorative stamp; as well as, a design for a fifty-cent piece for the Royal Canadian Mint. He was also commissioned by the University of Manitoba to paint a portrait of the Chacellor Harvey Secter and the Manitoba government to paint a portraits of Premier of Manitoba Gary Filmon and Gary Doer, and the Speakers of the House Louise Dacquay, Deni Rocan and George Hicks. In 2009 he was a winner of the Kingston Prize, Canada�s national portrait competition.

        Andrew has served or is serving on the board of the following organizations: Royal Canadian Academy of Arts, Winnipeg Art Gallery, Winnipeg, Manitoba; Site Gallery, Winnipeg, Manitoba; Border Crossings Magazine of the Arts, Winnipeg, Manitoba; and, Martha Street Studio, Winnipeg, Manitoba. He has also served as a juror on the Manitoba Arts Council Grand Juries.

        His work is represented in a wide range of public, corporate and private <strong>collections</strong>. These include: The Canada Council Art Bank, Ottawa, Ontario; Manitoba Art Council, Winnipeg, Manitoba; The Winnipeg Art Gallery, Winnipeg, Manitoba; University of Manitoba Faculty of Law, Winnipeg, Manitoba; University of Winnipeg, Winnipeg, Manitoba; Memorial University of Newfoundland Art Gallery, St Johns, Newfoundland; CKRC Broadcasting, Winnipeg, Manitoba; Alliance Francais, Winnipeg, Manitoba; Aquatic Hall of Fame, Winnipeg, Manitoba; The Claridge Collection / Bronfman Collection, Montreal, Quebec; Elizabeth Taylor, Los Angeles, California; Canada Post Corporation, Ottawa, Ontario; Manitoba Government, Winnipeg, Manitoba; Assante Asset Management Ltd., Winnipeg, Manitoba; Investors Group, Winnipeg, Manitoba; PriceWaterHouse Cooper, LLP, Vancouver, B.C.; Esso Petroleum, Calgary Alberta; The Nickle Art Museum, Calgary, Alberta; Great West Life, Winnipeg, Manitoba; Via Rail Canada, Inc., Montreal, Quebec; Wajima Holdings, Ltd., Calgary, Alberta; Suncor, Inc., Fort McMurray, Alberta; Burnet, Duckworth & Palmer LLP, Calgary, Alberta; Abex Financial Corp., Calgary, Alberta; Tecbau Technology, West Germany; Fairwood Foods Ltd., Hong Kong; Mahler Fine Art Inc., Seattle, Washington; West Coast Hotel Corporation, Seattle, Washington; the Royal Canadian Mint, Ottawa, Ontario; and Manitoba Hydro, Winnipeg, Manitoba

        The artist has travelled extensively through North America Europe Mexico, Japan, China, Taiwan, Hong Kong and Thailand. He is presently living and working in Winnipeg, Manitoba, with his wife Julia Lam and son Kalvin.		<br clear="all" />
    </div>
</div>
